describe('Chandigarh Trade Link app', () => {
  it('Visits the auth flow from the app root url', () => {
    cy.visit('/')
    cy.contains('ion-content', 'Chandigarh Trade Link')
    cy.contains('button', 'Register').click()
    cy.url().should('include', '/register')
    cy.contains('ion-content', 'Create an Account')
    cy.contains('button', 'Login').click()
    cy.url().should('include', '/login')
    cy.contains('button', 'Forgot Password?').click()
    cy.url().should('include', '/forgot-password')
    cy.contains('ion-content', 'Reset Password')
    cy.contains('ion-button', 'SEND RESET LINK').click()
    cy.url().should('include', '/reset-password')
    cy.contains('ion-content', 'UPDATE PASSWORD')
  })

  it('Visits the service catalog and product details flow', () => {
    cy.visit('/services')
    cy.contains('ion-content', 'Our Services')
    cy.contains('button', 'VIEW PRODUCTS').first().click()
    cy.url().should('include', '/services/concrete-admixture')
    cy.contains('ion-content', 'Concrete Admixture')
    cy.contains('button', 'VIEW DETAILS').first().click()
    cy.url().should('include', '/products/sikacim')
    cy.contains('ion-content', 'Usage Areas')
    cy.contains('button', 'Details').click()
    cy.url().should('include', '/products/sikacim/details')
    cy.contains('ion-content', 'Product Information')
    cy.contains('button', 'Application').click()
    cy.url().should('include', '/products/sikacim/application')
    cy.contains('ion-content', 'Application Information')
    cy.contains('button', 'Document').click()
    cy.url().should('include', '/products/sikacim/document')
    cy.contains('ion-content', 'Product Data Sheet')
  })

  it('Visits the contact and profile flow', () => {
    cy.visit('/contact')
    cy.contains('ion-content', 'Contact Us')
    cy.contains('ion-content', 'Punjab Head Office')
    cy.contains('ion-content', 'Other Branches')
    cy.get('ion-button[aria-label="Open profile"]').click()
    cy.url().should('include', '/profile')
    cy.contains('ion-content', 'My Profile')
    cy.contains('ion-content', 'Rajesh Kumar')
    cy.contains('button', 'Logout').click()
    cy.url().should('include', '/login')
  })
})
