describe('Chandigarh Trade Link app', () => {
  it('Visits the auth flow from the app root url', () => {
    cy.visit('/')
    cy.contains('ion-content', 'Chandigarh Trade Link')
    cy.contains('button', 'Admin Login').click()
    cy.get('input[name="email"]').should('have.value', '4dxjatt@gmail.com')
    cy.contains('button', 'Register').click()
    cy.url().should('include', '/register')
    cy.contains('ion-content', 'Create an Account')
    cy.visit('/login')
    cy.url().should('include', '/login')
    cy.contains('button', 'Forgot Password?').click()
    cy.url().should('include', '/forgot-password')
    cy.contains('ion-content', 'Reset Password')
    cy.contains('ion-button', 'SEND RESET LINK').click()
    cy.contains('ion-content', 'Email is required')
    cy.visit('/reset-password')
    cy.contains('ion-content', 'UPDATE PASSWORD')
    cy.visit('/login')
    cy.contains('ion-button', 'CONTINUE AS GUEST').click()
    cy.url().should('include', '/home')
    cy.contains('ion-content', 'Hello, Guest!')
    cy.get('button[aria-label="Guest account menu"]').first().click({ force: true })
    cy.contains('.ctl-account-dropdown button', 'Login')
    cy.contains('.ctl-account-dropdown button', 'Register')
    cy.get('[data-testid="main-menu-button"]').click({ force: true })
    cy.contains('ion-menu', 'Guest User')
    cy.contains('ion-menu', 'You are browsing as guest')
    cy.contains('ion-menu', 'LOGIN / REGISTER')
    cy.get('ion-menu').should('not.contain', 'My Quotes')
    cy.contains('ion-menu button', 'Request Quotation').click({ force: true })
    cy.url().should('include', '/quote')
    cy.contains('ion-content', 'Request Quotation')
    cy.get('input[name="phone"]')
      .type('9876543210', { force: true })
      .should('have.value', '9876543210')
    cy.get('input[name="productQuantities.sikacim"]')
      .type('50 kg', { force: true })
      .should('have.value', '50 kg')
    cy.get('input[name="productQuantities.sika-plastiment-2001-ns"]')
      .type('100 liters', { force: true })
      .should('have.value', '100 liters')
    cy.get('textarea[name="notes"]')
      .type('Urgent delivery required', { force: true })
      .should('have.value', 'Urgent delivery required')
    cy.contains('ion-content', 'SUBMIT REQUEST')
    cy.visit('/quotes')
    cy.contains('ion-content', 'My Quotes')
    cy.contains('ion-content', 'Login to view your quotes')
  })

  it('Protects admin routes for non-admin visitors', () => {
    cy.visit('/admin/dashboard')
    cy.url().should('include', '/login')
    cy.contains('ion-content', 'Chandigarh Trade Link')
  })

  it('Visits the service catalog and product details flow', () => {
    cy.visit('/services')
    cy.contains('ion-content', 'Our Services')
    cy.contains('button', 'VIEW PRODUCTS').first().click({ force: true })
    cy.url().should('include', '/services/concrete-admixture')
    cy.contains('ion-content', 'Concrete Admixture')
    cy.contains('button', 'VIEW DETAILS').first().click({ force: true })
    cy.url().should('include', '/products/sikacim')
    cy.contains('ion-content', 'Usage Areas')
    cy.visit('/products/sikacim/details')
    cy.contains('ion-content', 'Product Information')
    cy.visit('/products/sikacim/application')
    cy.contains('ion-content', 'Application Information')
    cy.visit('/products/sikacim/document')
    cy.contains('ion-content', 'Product Data Sheet')
  })

  it('Visits the contact and profile flow', () => {
    cy.visit('/contact')
    cy.contains('ion-content', 'Contact Us')
    cy.contains('ion-content', 'Punjab Head Office')
    cy.contains('ion-content', 'Other Branches')
    cy.visit('/profile')
    cy.contains('ion-content', 'My Profile')
    cy.contains('ion-content', 'Guest')
    cy.contains('button', 'Logout').click()
    cy.url().should('include', '/login')
  })
})
